theme: jekyll-theme-slate
title: AZ-104 - Training - Microsoft Azure Administrator 
description: Companion material and resources for the course 'Microsoft Azure Administrator' delivery by Ricardo Cabral 
relative_links:
  enabled: true
  collections: true
exclude:
  - .github/
include:
  - README.md
author: Ricardo Cabral
twitter_username: rramoscabral
github_username:  rramoscabral
